### ISSUE TITLE
what is the root password

### ISSUE THREAD

**Issue by 0xFF1E071F** [VSWSL/Arch-WSL#15]
Hello
Thanks for this repo.

I want to login as root! How can i do that? When I enter `su root` or just `su` I cannot login with my own user password? But my password works on sudo command.

Thank you

**Comment by vineelsai26** [comment]
there isn't and default root password set you have to set it yourself by typing `passwd`

**Comment by 0xFF1E071F** [comment]
Thank you.

For people who stuck like me in your user shell write down:
```txt
sudo passwd root
```
Then enter your credentials

close #15
