### ISSUE TITLE
pacman NOEXTRACT on man pages

### ISSUE THREAD

**Issue by rinchen** [VSWSL/Arch-WSL#16]
Hi,

In pacman.conf, noextract is set on man pages. That probably should not be set. (Took me a while today to figure out why man wasn't working.)  There are several other noextract options there as well that probably should be explained and/or removed.

**Comment by vineelsai26** [comment]
Hey, can you specify the exact code snippets on where it is giving the issue, and moreover I guess the problem is that I am using docker to extract the base image and to save storage it is disabled by default in the docker image, I will try to fix it by rewriting the pacman config with one from Arch ISO

**Comment by salvw** [comment]
Just delete 
`[options]
NoExtract  = usr/share/help/* !usr/share/help/en* !usr/share/help/C/*
NoExtract  = usr/share/gtk-doc/html/* usr/share/doc/*
NoExtract  = usr/share/locale/* usr/share/X11/locale/* usr/share/i18n/*
NoExtract   = !*locale*/en*/* !usr/share/i18n/charmaps/UTF-8.gz !usr/share/*locale*/locale.*
NoExtract   = !usr/share/*locales/en_?? !usr/share/*locales/i18n* !usr/share/*locales/iso*
NoExtract   = !usr/share/*locales/trans*
NoExtract   = !usr/share/X11/locale/C/*
NoExtract   = !usr/share/X11/locale/compose.dir !usr/share/X11/locale/iso8859-1/*
NoExtract  = !usr/share/*locales/C !usr/share/*locales/POSIX !usr/share/i18n/charmaps/ANSI_X3.4-1968.gz
NoExtract  = usr/share/man/* usr/share/info/*
NoExtract  = usr/share/vim/vim*/lang/*`

From /etc/pacman.conf

**Comment by rinchen** [comment]
Sorry got busy. What @salvw said. There are a bunch of NoExtract items in pacman.conf.
