### ISSUE TITLE
if this wsl-distribution don't support systemed?

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [VSWSL/Arch-WSL#17]
i run 
`sudo systemctl`

and i got this error 

`System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down`

if this wsl-distribution don't support **systemed**?

**Comment by vineelsai26** [comment]
WSL distros do not support systemd by default you have to enable it your self, refer this - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support

**Comment by TOLIE-OFFICIAL** [comment]
i add the wsl.conf file and restart the pc，but still get the same error
![image](https://github.com/VSWSL/Arch-WSL/assets/90889293/fe26d574-66f8-40a7-8ac9-32cb795a7885)

**Comment by TOLIE-OFFICIAL** [comment]
solved! thx

**Comment by TOLIE-OFFICIAL** [comment]
> @TOLIE-OFFICIAL Hey, how did you solve this problem? I can't seem to get it to work either.
> 
> Edit: I solved it. I had installed WSL the manual way as I didn't want to pre-install another distro. However this seems to give you an older version. So I disabled that WSL again via "Turn Windows features on and off" and then installed WSL again from the MS Store: https://aka.ms/wslstorepage. Now it works

there is a wsl.conf at "/etc/wsl.conf".If it do not exist,then make it.
```bash
[boot]
systemd=true
```
[click for more](https://learn.microsoft.com/zh-tw/windows/wsl/systemd)
