### ISSUE TITLE
ARM support need

### ISSUE THREAD

**Issue by SituChengxiang** [VSWSL/Arch-WSL#20]
Hi there,  
I have an arm PC that runs windows11, as microsoft wrote in his documents, wsl2 supports arm structure natively, I have tested it on ubuntu, and it really works well.  Therefore, I think it will have a better performance if my computer can run archlinuxarm instead of x86 version. Hope you can take it consideration and give me a reply at leisure.  
I'm Chinese and my English is not very well, if there are anything not so proper or even worse , please tell me about it, thank you.

**Comment by vineelsai26** [comment]
I haven't built an ARM version because haven't thought anyone would use it, since you want to use it ill build it for ARM as well

**Comment by SituChengxiang** [comment]
Thanks a miilion! If there is anything I can help, please contact me at your earliest convenience. I will get into a very busy period of time after 8th this month and may not capable to reply on time.
Thanks again for building!

**Comment by AquaBx** [comment]
Yes, that would be great. It would be useful to make Arch Linux for the Surface Pro X instead of using a docker.

**Comment by vineelsai26** [comment]
It seems that Arch Linux doesn't provide an Arm64 version for their docker images nor do they officially provide ARM64 ISOs to install on a VM so it would be difficult to provide regular builds from my side so I am closing the issue for now. I will try to build it if get my hands on a raspberry pi or some other ARM SBC.

**Comment by SituChengxiang** [comment]
Hi there, would you like to tell me about how to do that?  I have an arm pc on my hand and maybe I can provide some help.
(Archlinux arm official link: https://archlinuxarm.org/platforms/armv8, there is a link for Raspberry Pi 4;
there is a image for ARMv8 AArch64 Multi-platform devices at the link  https://archlinuxarm.org/about/downloads)

Please forgive my inappropriate expressions, English is not my native language and I'm learning it.

 Thanks for building again.

**Comment by vineelsai26** [comment]
Those are chipset specific images they can't be booted directly on other hardware but if you can do so, you can install it on your system and you extract the rootfs image from the instructions given here https://gitlab.archlinux.org/archlinux/archlinux-docker and publish a docker image, i think I can build from there

**Comment by AquaBx** [comment]
well, linux surface did a docker in order to build arm for the spx : https://github.com/linux-surface/aarch64-arch-mkimg

the rootfs is : https://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz

**Comment by vineelsai26** [comment]
cool, I will try with this

**Comment by AquaBx** [comment]
i'm also trying a github action to build a arch docker image for multiple architecture

**Comment by AquaBx** [comment]
better i found one that seems to work : https://hub.docker.com/r/menci/archlinuxarm

launched on podman on my surface and it seems fine

**Comment by vineelsai26** [comment]
This is working as well using it
<img width="641" alt="image" src="https://github.com/VSWSL/Arch-WSL/assets/52851879/ecde7b8e-f780-4564-a63b-352612c64ee7">


> well, linux surface did a docker in order to build arm for the spx : https://github.com/linux-surface/aarch64-arch-mkimg
> 
> the rootfs is : https://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz

**Comment by AquaBx** [comment]
oh cool

**Comment by AquaBx** [comment]
yup, i built my one and it is working fine 👍

**Comment by AquaBx** [comment]
![Capture d'écran 2023-08-06 213605](https://github.com/VSWSL/Arch-WSL/assets/35542432/111c4a3d-df66-4ff7-a09b-7474d90cb013)

**Comment by AquaBx** [comment]
I made a pull request in order to build the image properly.
With that, we can probably do the same with Fedora

**Comment by vineelsai26** [comment]
added on #21
