### ISSUE TITLE
sussy WLS window icon

### ISSUE THREAD

**Issue by k-i-o** [VSWSL/Arch-WSL#28]
![image](https://github.com/VSWSL/Arch-WSL/assets/68398653/02286a86-c3d1-48cf-9d54-31d6761d225c)

**Comment by vineelsai26** [comment]
need more context on exactly what the issues is, closing the issue as no useful information is provided, reopen if you are willing to provide additional details on what terminal you are using and when you are getting the icon and any other details that can be used for replicating the issue

**Comment by k-i-o** [comment]
I just installed arch WSL and it appear without an image everywhere, also in the windows (10) tab in the section recent apps
