### ISSUE TITLE
Pacman too far out of date

### ISSUE THREAD

**Issue by Katherine1** [VSWSL/Arch-WSL#29]
Several months back, Arch did a big move to GIT packaging (see https://archlinux.org/news/git-migration-completed/ ) This required a pacman update. At this point, a new install of this ArchWSL comes with a version of pacman that can't actually get package sources anymore. The base Arch system needs to be updated to a point after the GIT migration.

**Comment by vineelsai26** [comment]
I'll rebuild and publish this weekend then

**Comment by Katherine1** [comment]
Perfect, thanks

**Comment by vineelsai26** [comment]
fixed in latest release
