### ISSUE TITLE
Cannot install yay/pakku as AUR helper in WSL1

### ISSUE THREAD

**Issue by dtantono** [VSWSL/Arch-WSL#36]
Hi
I tried to install aur helper. But, it does not work. What do you think?
![image](https://github.com/VSWSL/Arch-WSL/assets/29157187/00126c23-ead3-4bae-a280-5e1d64c514af)
![image](https://github.com/VSWSL/Arch-WSL/assets/29157187/7c26063e-3e57-4cd7-826f-3d74213af54e)

**Comment by vineelsai26** [comment]
https://github.com/Jguer/yay/issues/1227 try this

**Comment by dtantono** [comment]
hold on, So, this problem only happens on WSL1. is that so?

**Comment by vineelsai26** [comment]
seems like it, I was able to replicate it as well on WSL 1
<img width="1172" alt="image" src="https://github.com/VSWSL/Arch-WSL/assets/52851879/1ed89568-0c27-498f-80de-529c6908949b">

**Comment by dtantono** [comment]
Ok, that will be quite long and I want to make sure. So, to sum up the current workaround is:
1. cd /tmp
2. wget http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.31.orig.tar.gz
3. ./bootstrap
4. ./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp
5. make
6. sudo make install
7. export PATH="/opt/fakeroot/bin:$PATH"
8. git clone https://aur.archlinux.org/yay.git
9. cd yay
10. makepkg -si
11. yay -Syu fakeroot-tcp
Is that so?

**Comment by vineelsai26** [comment]
You have to try that for yourself I mostly use Windows only on VMs these days, so if you don't want to do the whole ordeal I guess you can download yay from my repo and just do the last step - https://github.com/vineelsai26/repo/tree/main/linux/arch/x86_64

**Comment by dtantono** [comment]
Hold on, Sorry, what is the right command?

**Comment by dtantono** [comment]
Sorry for multiple response. But, it seems it does not worked
![image](https://github.com/VSWSL/Arch-WSL/assets/29157187/99b78a9b-0aa7-4d31-978b-9c197f4c9719)

**Comment by vineelsai26** [comment]
You have to get it with raw link if you directly use GitHub link it will download a web page. use this link to download https://github.com/vineelsai26/repo/raw/main/linux/arch/x86_64/yay-12.2.0-1-x86_64.pkg.tar.zst

**Comment by dtantono** [comment]
Yeah, I can install yay with that file. But, yay cannot install other aur helper and other cli apps with same error. What do you think?
![Snipaste_2024-01-14_17-40-52](https://github.com/VSWSL/Arch-WSL/assets/29157187/d4e3689a-3212-4a78-9c31-0b56a55a1d5a)
![Snipaste_2024-01-14_17-30-53](https://github.com/VSWSL/Arch-WSL/assets/29157187/7a97ca18-cebc-4c44-a30c-637e680a3dd6)
![Snipaste_2024-01-14_17-30-31](https://github.com/VSWSL/Arch-WSL/assets/29157187/861559a2-c46b-448e-8ee8-97e00ce26e3d)

**Comment by vineelsai26** [comment]
did you install `fakeroot-tcp`? if not try that, if that didn't work you have to install this version of fakeroot and then install fakeroot-tcp

> Ok, that will be quite long and I want to make sure. So, to sum up the current workaround is:
> 
> 1. cd /tmp
> 2. wget http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.31.orig.tar.gz
> 3. ./bootstrap
> 4. ./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp
> 5. make
> 6. sudo make install
> 7. export PATH="/opt/fakeroot/bin:$PATH"
> 8. git clone https://aur.archlinux.org/yay.git
> 9. cd yay
> 10. makepkg -si
> 11. yay -Syu fakeroot-tcp
>     Is that so?

**Comment by dtantono** [comment]
Hi
I did it for fakeroot-tcp with pacman. But, since it is not pacman. I tried it on AUR for fakeroot-tcp. But, the fakeroot-tcp is not working well. 
![Snipaste_2024-01-14_20-29-27](https://github.com/VSWSL/Arch-WSL/assets/29157187/aba1aa59-3690-4d07-89e9-1ae70c5fb604)
![Snipaste_2024-01-14_20-25-45](https://github.com/VSWSL/Arch-WSL/assets/29157187/4709c202-bcbc-439a-b232-756df038c2de)

**Comment by vineelsai26** [comment]
then I guess try the steps mentioned in the issue 

> [Jguer/yay#1227](https://github.com/Jguer/yay/issues/1227) try this

**Comment by vineelsai26** [comment]
any reason why you are not using WSL 2?

**Comment by dtantono** [comment]
Yeah I did that workaround. and I got new error again. The reason I stick to WSL 1 because it use hyper v and it is interrupt my virtualisation programs. 
![Snipaste_2024-01-14_22-33-50](https://github.com/VSWSL/Arch-WSL/assets/29157187/c110368f-7bc6-4d94-9bb1-97881d712ef5)
![Snipaste_2024-01-14_22-34-19](https://github.com/VSWSL/Arch-WSL/assets/29157187/865b5064-c69f-47d5-99a1-ba90bfa5cbea)

**Comment by vineelsai26** [comment]
> Ok, that will be quite long and I want to make sure. So, to sum up the current workaround is:
> 
> 1. cd /tmp
> 2. wget http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.31.orig.tar.gz
> 3. ./bootstrap
> 4. ./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp
> 5. make
> 6. sudo make install
> 7. export PATH="/opt/fakeroot/bin:$PATH"
> 8. git clone https://aur.archlinux.org/yay.git
> 9. cd yay
> 10. makepkg -si
> 11. yay -Syu fakeroot-tcp
>     Is that so?

4th step is probably supposed to be `./configure --prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp` not `./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp`

**Comment by dtantono** [comment]
Hi
I checked this issue and I found this (https://wsldl-pg.github.io/ArchW-docs/Known-issues/) I need to run this command
wget https://github.com/yuk7/arch-prebuilt/releases/download/18082100/fakeroot-tcp-1.23-1-x86_64.pkg.tar.xz
and sudo pacman -U fakeroot-tcp-1.23-1-x86_64.pkg.tar.xz
to make it work 

So, I hope you can update faq. if the problem arises
