### ISSUE TITLE
Remove /.dockerenv

### ISSUE THREAD

**Issue by klercke** [VSWSL/Arch-WSL#37]
There is a .dockerenv file in the root of the filesystem. This can confuse certain pieces of software and make them think they are running under a Docker environment. Sharship, for example, runs into this issue. If possible, could this file be removed from the filesystem as part of the installation process?

**Comment by vineelsai26** [comment]
`.dockerenv` file is already being removed from newer versions published after Aug 6, 2023, you might have upgraded from an older version

**Comment by tmewett** [comment]
I installed from the Windows Store yesterday, and I still have a `/.dockerenv`, last modified 2 March 2024
