### ISSUE TITLE
Opening programs via WSL2 does not work

### ISSUE THREAD

**Issue by t3df1** [VSWSL/Arch-WSL#42]
I have Arch and Ubuntu installed in WSL (ver. 2), I installed nautilus and qt5(and 6)+qtcreator on both.
In Arch, I get errors when running **nautilus** 
![image](https://github.com/VSWSL/Arch-WSL/assets/164526938/541cd497-aaea-4646-8267-dda65a40740d)
and **qtcreator**
![image](https://github.com/VSWSL/Arch-WSL/assets/164526938/9a8bbb10-6188-4c69-b9f8-0d0638905c71)
To be honest, I've checked other programs, they don't work either, like gedit. Many people gave the same type of error `Error: Can't open display: :0` as in qtcreator, most likely nautilus does not start for the same reason
There are no similar problems in Ubuntu, what could this be related to?

**Comment by hgarfer** [comment]
was able to open GUI applications by manually creating a needed symlink, that is:
`ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix`
taken from https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#x11-display-socket

**Comment by nocompyle** [comment]
> @t3df1 was able to open GUI applications by manually creating a needed symlink, that is: `ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix` taken from https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#x11-display-socket

```
sudo rm -r/tmp/.X11-unix
ln -s/mnt/wslg/.X11-unix/tmp/.X11-unix
``` 
Worked for me. There are some errors in the terminal during startup, but nevertheless the programs run. Thanks!

**Comment by t3df1** [comment]
> @t3df1 was able to open GUI applications by manually creating a needed symlink, that is: `ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix` taken from https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#x11-display-socket

```
sudo rm -r/tmp/.X11-unix
ln -s/mnt/wslg/.X11-unix/tmp/.X11-unix
``` 
Worked for me. There are some errors in the terminal during startup, but nevertheless the programs run. Thanks!

**Comment by t3df1** [comment]
> @t3df1 was able to open GUI applications by manually creating a needed symlink, that is: `ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix` taken from https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#x11-display-socket

It really worked for me, but after restarting Arch in the terminal, this file is deleted from me and it needs to be created. Do you know what the problem might be?

**Comment by t3df1** [comment]
Ok, I found a solution that will apparently create a link using systemd. I think this is the only solution at the moment. Here is the solution [microsoft/wslg/issues/43](https://github.com/microsoft/wslg/issues/43#issuecomment-826039096)

**Comment by hgarfer** [comment]
thanks, actually i was having the same issue 😅 , in my case I copied all my config from an ArcoLinux native install so I assumed something was copied that was overwriting it, will try yours!
